/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kommunikationssystem;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionListener;
import oru.inf.*;
import oru.inf.InfDB;
/**
 *
 * @author Jerka
 */
public class AdminTaBortInlagg extends javax.swing.JFrame {
 private InfDB db;
 private static String id;
    
 
    /*
    /**
     * Creates new form AdminTaBortInlagg
     */
    public AdminTaBortInlagg(InfDB db) {
        initComponents();
        this.db = db;
        listaInlagg();
        populateComboBox();
        populateComboBoxKategori();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jToggleButton2 = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        comboBoxForfattare = new javax.swing.JComboBox<>();
        comboBoxKategori = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        itemStartsida1 = new javax.swing.JMenuItem();
        itemVisaInformellaBlogg1 = new javax.swing.JMenuItem();
        itemPubliceraInlagg1 = new javax.swing.JMenuItem();
        itemTaBortInlagg1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        itemKonto1 = new javax.swing.JMenuItem();
        itemTaBortKonto1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        itemAllmanKalender1 = new javax.swing.JMenuItem();
        itemPrivatKalender1 = new javax.swing.JMenuItem();
        itemMinaMoten1 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        itemSkapaMote1 = new javax.swing.JMenuItem();
        itemLoggaUt1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButton1.setText("Ta bort");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jToggleButton2.setText("Ta bort alla....");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Du ändrar på inlägget:");

        jLabel1.setText("Inget inlägg har valts...");

        jLabel3.setText("ID  TITEL       TEXT");

        jToggleButton3.setText("Uppdatera");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Titel");

        comboBoxForfattare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxForfattareActionPerformed(evt);
            }
        });

        btnBack.setText("Tillbaka");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                        .addComponent(jToggleButton2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(43, 43, 43)
                                                .addComponent(comboBoxKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jToggleButton3)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboBoxForfattare, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton3)
                            .addComponent(comboBoxForfattare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton1)
                            .addComponent(jToggleButton2))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack))))
        );

        jMenu4.setText("Inlägg");

        itemStartsida1.setText("Startsida");
        itemStartsida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemStartsida1ActionPerformed(evt);
            }
        });
        jMenu4.add(itemStartsida1);

        itemVisaInformellaBlogg1.setText("Visa blogg");
        itemVisaInformellaBlogg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVisaInformellaBlogg1ActionPerformed(evt);
            }
        });
        jMenu4.add(itemVisaInformellaBlogg1);

        itemPubliceraInlagg1.setText("Publicera inlägg");
        itemPubliceraInlagg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPubliceraInlagg1ActionPerformed(evt);
            }
        });
        jMenu4.add(itemPubliceraInlagg1);

        itemTaBortInlagg1.setText("Ta bort inlägg");
        itemTaBortInlagg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTaBortInlagg1ActionPerformed(evt);
            }
        });
        jMenu4.add(itemTaBortInlagg1);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Kontohantering");

        itemKonto1.setText("Ändra konto uppgifter");
        itemKonto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemKonto1ActionPerformed(evt);
            }
        });
        jMenu5.add(itemKonto1);

        itemTaBortKonto1.setText("Ta bort konton");
        itemTaBortKonto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTaBortKonto1ActionPerformed(evt);
            }
        });
        jMenu5.add(itemTaBortKonto1);

        jMenuBar2.add(jMenu5);

        jMenu6.setText("Kalender");

        itemAllmanKalender1.setText("Visa allmänna möten");
        itemAllmanKalender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAllmanKalender1ActionPerformed(evt);
            }
        });
        jMenu6.add(itemAllmanKalender1);

        itemPrivatKalender1.setText("Visa privat kalender");
        itemPrivatKalender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPrivatKalender1ActionPerformed(evt);
            }
        });
        jMenu6.add(itemPrivatKalender1);

        jMenuBar2.add(jMenu6);

        itemMinaMoten1.setText("Möten");

        jMenuItem8.setText("Visa mina möten");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        itemMinaMoten1.add(jMenuItem8);

        itemSkapaMote1.setText("Skapa möte");
        itemSkapaMote1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSkapaMote1ActionPerformed(evt);
            }
        });
        itemMinaMoten1.add(itemSkapaMote1);

        jMenuBar2.add(itemMinaMoten1);

        itemLoggaUt1.setText(" Logga ut");
        itemLoggaUt1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        itemLoggaUt1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jMenuItem2.setText("Logga ut");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        itemLoggaUt1.add(jMenuItem2);

        jMenuBar2.add(itemLoggaUt1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        DefaultListModel list = (DefaultListModel) jList1.getModel();
          
        String varde = jList1.getSelectedValue();
        if (varde != null){
        int svar = JOptionPane.showConfirmDialog(this, "Är du säker på att du vill ta bort följande inlägg: "+varde+"?","Confrim", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
     switch (svar) {
         case JOptionPane.YES_OPTION:
             String[] inlagg = varde.split(" ", 3);
           
        for (String inlagg1 : inlagg) {
            String BID = inlagg[0];

            
                
                
                try {
                 
                    String sql2 = "DELETE FROM BLOGGINLAGG WHERE BID =" + BID + "";
                  String sql3 = "DELETE FROM BLOGGINLAGG_KOMENTAR WHERE BID =" + BID + "";
                    db.delete(sql3);
                    db.delete(sql2);
                    
                } catch (InfException e) {
                    System.out.println(e.getMessage());
                }
            }
            list.removeElement(jList1.getSelectedValue());
             JOptionPane.showMessageDialog(null, "Inlagget har tagits bort");
             break;

     
         case JOptionPane.NO_OPTION:
             break;
         case JOptionPane.CLOSED_OPTION:
             break;
         default:
             break;
     }}else if(varde == null){
     JOptionPane.showMessageDialog(null, "Inget av inläggen har valts");
     }
        listaInlagg();
        
        
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
      
        int result = JOptionPane.showConfirmDialog(null, 
   "Är du säker på att du vill ta bort alla blogginlägg?",null, JOptionPane.YES_NO_OPTION);
if(result == JOptionPane.NO_OPTION) {
    
} 
else if(result == JOptionPane.YES_OPTION){
        try{
      String sql = "DELETE FROM BLOGGINLAGG";
     
        db.delete(sql);
        JOptionPane.showMessageDialog(null, "Alla av inläggen har tagits bort");
        }
        catch (InfException e) {
                    System.out.println(e.getMessage());
                }
}
        
         listaInlagg();

    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        
        
        //UPPDATERA
        
String varde = jList1.getSelectedValue();




         DefaultListModel list = (DefaultListModel) jList1.getModel();
         
        
         
         if(varde != null){
       
         String[] inlagg = varde.split(" ", 3);
         
          for (String inlagg1 : inlagg) {
            String BID = inlagg[0];
            String titel = inlagg[0];
            String text = inlagg[1];
            
              
                 
                  
                 
                  
                  if (Validation.isNotEmpty(jTextField1) && Validation.isNotEmpty(jTextField2)) {
                  String TitelInput = jTextField1.getText();
                   String TextInput =  jTextField2.getText();
                 
                  String ForfattareInput = comboBoxForfattare.getSelectedItem().toString();
                  String KategoriInput = comboBoxKategori.getSelectedItem().toString();
                   try { 
                  
                
                 String sql = "SELECT AID FROM ANSTALLDA WHERE NAMN = '"+ForfattareInput+"'";
                 String sqlKat="SELECT KID FROM KATEGORI WHERE KATEGORINAMN = '"+KategoriInput+"'";
                 String hamtadAID = db.fetchSingle(sql);
                 String hamtadKID = db.fetchSingle(sqlKat);
                 
                 
      
        String Uppdatera = "UPDATE BLOGGINLAGG SET TITEL = '"+TitelInput+"', Text = '"+TextInput+"', FORFATTARE = '"+hamtadAID+"', KATEGORI = '"+hamtadKID+"'WHERE BID ='" + BID + "'";
        db.update(Uppdatera);
         
        
               
                  
                    
                   
                    
                } catch (InfException e) {
                    System.out.println(e.getMessage());
                }}
            }}else if(varde == null){
            
            {
     JOptionPane.showMessageDialog(null, "Inget av inläggen har valts");
             }
            }
                            

         
       
     
    
     
        listaInlagg();
          
          
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        
        String inlaggText = "";

        inlaggText = String.valueOf(jList1.getSelectedValue());
        jLabel1.setText(inlaggText);
        
    }//GEN-LAST:event_jList1MouseClicked

    private void comboBoxForfattareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxForfattareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxForfattareActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

    }//GEN-LAST:event_btnBackActionPerformed

    private void itemStartsida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemStartsida1ActionPerformed
        // TODO add your handling code here:
        AdminVisaInlägg startSidaWindow = new AdminVisaInlägg(db);
        startSidaWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_itemStartsida1ActionPerformed

    private void itemVisaInformellaBlogg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVisaInformellaBlogg1ActionPerformed
        // TODO add your handling code here:
        AdminVisaInlägg startSidaWindow = new AdminVisaInlägg(db);
        startSidaWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_itemVisaInformellaBlogg1ActionPerformed

    private void itemPubliceraInlagg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPubliceraInlagg1ActionPerformed
        // TODO add your handling code here:
        AdminGöraInlägg startSidaWindow = new AdminGöraInlägg(db);
        startSidaWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_itemPubliceraInlagg1ActionPerformed

    private void itemTaBortInlagg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTaBortInlagg1ActionPerformed
        // TODO add your handling code here:
        AdminTaBortInlagg startSidaWindow = new AdminTaBortInlagg(db);
        startSidaWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_itemTaBortInlagg1ActionPerformed

    private void itemKonto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemKonto1ActionPerformed
        // TODO add your handling code here:
        Konto startSidaWindow = new Konto(db);
        startSidaWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_itemKonto1ActionPerformed

    private void itemTaBortKonto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTaBortKonto1ActionPerformed
        // TODO add your handling code here:
        AdminTaBortKonto startSidaWindow = new AdminTaBortKonto(db);
        startSidaWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_itemTaBortKonto1ActionPerformed

    private void itemAllmanKalender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAllmanKalender1ActionPerformed
        // TODO add your handling code here:
        AdminKalender startSidaWindow = new AdminKalender(db);
        startSidaWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_itemAllmanKalender1ActionPerformed

    private void itemPrivatKalender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPrivatKalender1ActionPerformed
        // TODO add your handling code here:
        AdminPrivatKalender startSidaWindow = new AdminPrivatKalender(db);
        startSidaWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_itemPrivatKalender1ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        AdminMinaMoten startSidaWindow = new AdminMinaMoten(db);
        startSidaWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void itemSkapaMote1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSkapaMote1ActionPerformed
        // TODO add your handling code here:
        AdminLaggaInMoten startSidaWindow = new AdminLaggaInMoten(db);
        startSidaWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_itemSkapaMote1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        MainWindow startSidaWindow = new MainWindow(db);
        startSidaWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminTaBortInlagg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminTaBortInlagg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminTaBortInlagg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminTaBortInlagg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               //new AdminTaBortInlagg().setVisible(true);
            }
        });
    }
   
    public void listaInlagg(){
         DefaultListModel list = new DefaultListModel();
        jList1.clearSelection();
        
        try {  
            ArrayList<HashMap<String, String>> blogginlagg;
            String sql = "SELECT BID, TITEL, TEXT FROM BLOGGINLAGG";
            
            blogginlagg = db.fetchRows(sql);
            if(blogginlagg !=null){

            for (HashMap<String, String> hittad : blogginlagg) {
                String BID = hittad.get("BID");
                String titel = hittad.get("TITEL");
                String text = hittad.get("TEXT");
                              
                
                
                list.addElement(BID + " " + titel +" "+text );
                jList1.setModel(list);
            }}else{ jList1.setModel(list);
            list.addElement("Det finns inga inlägg i databasen.");
            String varde = jList1.getSelectedValue();
            jLabel1.setText(varde);
                    }
            
        } catch (InfException e) {
            System.out.println(e.getMessage());
        }
    }
    public void populateComboBox(){
        
        try {  

          ArrayList<String> Forfattare;
          
          String SQLForfattare = "SELECT NAMN FROM ANSTALLDA";
          
            Forfattare = db.fetchColumn(SQLForfattare);
            

            
            for (String resultat : Forfattare) {
                comboBoxForfattare.addItem(resultat);
            }
           
        } catch (InfException e) {
            e.printStackTrace();
        }
    }
        public void populateComboBoxKategori(){
            try{
         ArrayList<String> Kategorier;
         String SQLKategorier = "SELECT KATEGORINAMN FROM KATEGORI";
         Kategorier = db.fetchColumn(SQLKategorier);
            for (String kategori :Kategorier ){
            comboBoxKategori.addItem(kategori);
            }
        }
         catch(InfException e) {
            e.printStackTrace();
        }}

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> comboBoxForfattare;
    private javax.swing.JComboBox<String> comboBoxKategori;
    private javax.swing.JMenuItem itemAllmanKalender1;
    private javax.swing.JMenuItem itemKonto1;
    private javax.swing.JMenu itemLoggaUt1;
    private javax.swing.JMenu itemMinaMoten1;
    private javax.swing.JMenuItem itemPrivatKalender1;
    private javax.swing.JMenuItem itemPubliceraInlagg1;
    private javax.swing.JMenuItem itemSkapaMote1;
    private javax.swing.JMenuItem itemStartsida1;
    private javax.swing.JMenuItem itemTaBortInlagg1;
    private javax.swing.JMenuItem itemTaBortKonto1;
    private javax.swing.JMenuItem itemVisaInformellaBlogg1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
