/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kommunikationssystem;

import oru.inf.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Haag
 */
public class Konto extends javax.swing.JFrame {
    
    private static InfDB idb;
    private String aid;

    /**
     * Creates new form Konto
     */
    public Konto(InfDB idb) {
        this.idb = idb;
        initComponents();
        aid = MainWindow.getId();
        fillfield();
    }
    
    private void fillfield() {
    
    
    try {
        String Name = idb.fetchSingle("SELECT NAMN FROM ANSTALLDA WHERE AID = " + "'" + aid + "'");
        txtName.setText(Name);
        
        String Lastname = idb.fetchSingle("SELECT EFTERNAMN FROM ANSTALLDA WHERE AID = " + "'" + aid + "'");
        txtLastname.setText(Lastname);
        
        String Mail = idb.fetchSingle("SELECT EMAIL FROM ANSTALLDA WHERE AID = " + "'" + aid + "'");
        txtmail.setText(Mail);
        
        String Phone = idb.fetchSingle("SELECT TELEFON FROM ANSTALLDA WHERE AID = " + "'" + aid + "'");
        txtPhone.setText(Phone);
        
        String TRoll = idb.fetchSingle("SELECT RID FROM ROLLER_ANSTALLDA WHERE AID= " + "'" + aid + "'" + "AND RID ='" + 2 + "'");
        if (TRoll != null) {
                    rbTeacher.setSelected(true);
                } else {
                    rbTeacher.setSelected(false);
                }
       
        String SRoll = idb.fetchSingle("SELECT RID FROM ROLLER_ANSTALLDA WHERE AID= " + "'" + aid + "'" + "AND RID ='" + 3 + "'");
        if (SRoll != null) {
                    rbSience.setSelected(true);
                } else {
                    rbSience.setSelected(false);
                }
        
        String Notis = idb.fetchSingle("SELECT NOTIS FROM ANSTALLDA WHERE AID= " + aid );
        if (Notis != null)
        {    
            if (Notis.equals("J")) {
                    rbNotis.setSelected(true);
                } 
            else {
                    rbNotis.setSelected(false);
                }
        }
    }
    catch (InfException e) {
        JOptionPane.showMessageDialog(null, "Ett fel inträffade!");
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAccount = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lablemail = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        lablePhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        btnChange1 = new javax.swing.JButton();
        btnPassword = new javax.swing.JButton();
        rbTeacher = new javax.swing.JRadioButton();
        rbSience = new javax.swing.JRadioButton();
        txtLastname = new javax.swing.JTextField();
        labelLastname = new javax.swing.JLabel();
        rbNotis = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        itemStartsida = new javax.swing.JMenuItem();
        itemVisaInformellaBlogg = new javax.swing.JMenuItem();
        itemPubliceraInlagg = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        itemKonto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemAllmanKalender = new javax.swing.JMenuItem();
        itemPrivatKalender = new javax.swing.JMenuItem();
        itemMinaMoten = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        itemSkapaMote = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelAccount.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        labelAccount.setText("Konto");

        labelName.setText("Förnamn");

        lablemail.setText("Email");

        lablePhone.setText("Telefon");

        btnChange1.setText("Ändra information");
        btnChange1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChange1ActionPerformed(evt);
            }
        });

        btnPassword.setText("Ändra lösenord");
        btnPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasswordActionPerformed(evt);
            }
        });

        rbTeacher.setText("Lärare");

        rbSience.setText("Forskare");

        labelLastname.setText("Efternamn");

        rbNotis.setText("Email notis inlägg");

        jMenu3.setText("Inlägg");

        itemStartsida.setText("Startsida");
        itemStartsida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemStartsidaActionPerformed(evt);
            }
        });
        jMenu3.add(itemStartsida);

        itemVisaInformellaBlogg.setText("Visa blogg");
        jMenu3.add(itemVisaInformellaBlogg);

        itemPubliceraInlagg.setText("Publicera inlägg");
        itemPubliceraInlagg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPubliceraInlaggActionPerformed(evt);
            }
        });
        jMenu3.add(itemPubliceraInlagg);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Kontohantering");

        itemKonto.setText("Ändra konto uppgifter");
        itemKonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemKontoActionPerformed(evt);
            }
        });
        jMenu1.add(itemKonto);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Kalender");

        itemAllmanKalender.setText("Visa allmänna möten");
        itemAllmanKalender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAllmanKalenderActionPerformed(evt);
            }
        });
        jMenu2.add(itemAllmanKalender);

        itemPrivatKalender.setText("Visa privat kalender");
        itemPrivatKalender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPrivatKalenderActionPerformed(evt);
            }
        });
        jMenu2.add(itemPrivatKalender);

        jMenuBar1.add(jMenu2);

        itemMinaMoten.setText("Möten");

        jMenuItem7.setText("Visa mina möten");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        itemMinaMoten.add(jMenuItem7);

        itemSkapaMote.setText("Skapa möte");
        itemSkapaMote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSkapaMoteActionPerformed(evt);
            }
        });
        itemMinaMoten.add(itemSkapaMote);

        jMenuBar1.add(itemMinaMoten);

        jMenu4.setText("Logga ut");

        jMenuItem1.setText("Logga ut");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPassword)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lablePhone)
                                .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lablemail)
                                .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelLastname)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelName))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(rbNotis)))
                .addGap(0, 23, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(rbSience)
                        .addGap(55, 55, 55)
                        .addComponent(rbTeacher))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnChange1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(labelAccount)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(labelAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLastname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lablemail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lablePhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSience)
                    .addComponent(rbTeacher))
                .addGap(36, 36, 36)
                .addComponent(rbNotis)
                .addGap(18, 18, 18)
                .addComponent(btnChange1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnPassword)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasswordActionPerformed
        Password password = new Password(idb);
        password.setVisible(true);
    }//GEN-LAST:event_btnPasswordActionPerformed

    private void btnChange1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChange1ActionPerformed
         if (Validation.isNotEmpty(txtName,txtLastname,txtmail,txtPhone) && Validation.isInteger(txtPhone)){
             int id= Integer.parseInt(aid);
             // Frågar om man vill utföra ändring
            int input = JOptionPane.showConfirmDialog(null, "Är du säker på att du vill ändra informationen?", "Ändra information..", 2);
            
            if (input == 0) {
                String Name = txtName.getText();
                String Lastname = txtLastname.getText();
                String Mail = txtmail.getText();
                String Phone = txtPhone.getText();
                String Notis = "";
                
                try {
                    idb.update("UPDATE ANSTALLDA SET NAMN = " + "'" + Name + "'" + "WHERE AID = " + "'" + id + "'");
                    idb.update("UPDATE ANSTALLDA SET EFTERNAMN = " + "'" + Lastname + "'" + "WHERE AID = " + "'" + id + "'");
                    idb.update("UPDATE ANSTALLDA SET EMAIL = " + "'" + Mail + "'" + "WHERE AID = " + "'" + id + "'");
                    idb.update("UPDATE ANSTALLDA SET TELEFON = " + "'" + Phone + "'" + "WHERE AID = " + "'" + id + "'");
                    
                    if (rbTeacher.isSelected()) {
                        idb.delete("DELETE FROM ROLLER_ANSTALLDA WHERE AID= " + "'" + id + "'" + "AND RID ='" + 2 + "'");
                        idb.insert("INSERT INTO ROLLER_ANSTALLDA VALUES ('" + 2 + "','" + id + "')");
                    } 
                    else {
                        idb.delete("DELETE FROM ROLLER_ANSTALLDA WHERE AID= " + "'" + id + "'" + "AND RID ='" + 2 + "'");
                    }
                    
                    if (rbSience.isSelected()) {
                        idb.delete("DELETE FROM ROLLER_ANSTALLDA WHERE AID= " + "'" + id + "'" + "AND RID ='" + 3 + "'");
                        idb.insert("INSERT INTO ROLLER_ANSTALLDA VALUES ('" + 3 + "','" + id + "')");
                    } 
                    else {
                        idb.delete("DELETE FROM ROLLER_ANSTALLDA WHERE AID= " + "'" + id + "'" + "AND RID ='" + 3 + "'");
                    }
                    
                    if (rbNotis.isSelected()) {
                    Notis = "J";
                    } 
                    else {
                    Notis = "N";
                    }
                    idb.update("UPDATE ANSTALLDA SET NOTIS = '" + Notis +"' WHERE AID ='" + id + "'");
                    JOptionPane.showMessageDialog(null, "Profilen har uppdaterats");
                }
                catch (InfException e) {
                    JOptionPane.showMessageDialog(null, "Ett fel inträffade!");
                }
            }
         }
    }//GEN-LAST:event_btnChange1ActionPerformed

    private void itemStartsidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemStartsidaActionPerformed
        new VisaInlägg(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_itemStartsidaActionPerformed

    private void itemPubliceraInlaggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPubliceraInlaggActionPerformed

        new GöraInlägg(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_itemPubliceraInlaggActionPerformed

    private void itemKontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemKontoActionPerformed
        new Konto(idb).setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_itemKontoActionPerformed

    private void itemAllmanKalenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAllmanKalenderActionPerformed
        new Kalender(idb).setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_itemAllmanKalenderActionPerformed

    private void itemPrivatKalenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPrivatKalenderActionPerformed
        // TODO add your handling code here:
        new PrivatKalender(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_itemPrivatKalenderActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

        new MinaMoten(idb).setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void itemSkapaMoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSkapaMoteActionPerformed

        new LaggaInMoten(idb).setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_itemSkapaMoteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new MainWindow(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Konto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Konto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Konto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Konto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Konto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange1;
    private javax.swing.JButton btnPassword;
    private javax.swing.JMenuItem itemAllmanKalender;
    private javax.swing.JMenuItem itemKonto;
    private javax.swing.JMenu itemMinaMoten;
    private javax.swing.JMenuItem itemPrivatKalender;
    private javax.swing.JMenuItem itemPubliceraInlagg;
    private javax.swing.JMenuItem itemSkapaMote;
    private javax.swing.JMenuItem itemStartsida;
    private javax.swing.JMenuItem itemVisaInformellaBlogg;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JLabel labelAccount;
    private javax.swing.JLabel labelLastname;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel lablePhone;
    private javax.swing.JLabel lablemail;
    private javax.swing.JRadioButton rbNotis;
    private javax.swing.JRadioButton rbSience;
    private javax.swing.JRadioButton rbTeacher;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtmail;
    // End of variables declaration//GEN-END:variables
}
